#!/usr/bin/env bash

PROGRAM=$(basename $0)
MEAT_DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

sub_help() {
	cat <<HELP_USAGE

*** MEAT ***

Usage: $PROGRAM <subcommand> [options]

Subcommands:
	find_replace_filenames - Replace all occurrences of the search string in files with the replacement string.

Aliases:
	frf - find_replace_filenames

For help with each subcommand run:
$PROGRAM <subcommand> -h|--help
HELP_USAGE
}

source "$MEAT_DIR/bin/find_replace_filenames"

subcommand=$1
case $subcommand in
"" | "-h" | "--help")
	sub_help
	;;
*)
	shift
	(sub_${subcommand} $@) 2>/dev/null
	if [ $? = 127 ]; then
		cat <<HELP_ERROR
Error: '$subcommand' is not a known subcommand.
	Run '$PROGRAM --help' for a list of known subcommands.
HELP_ERROR
		exit 1
	fi
	;;
esac
